export const photography = [
  'photo',
  'photographer',
  'camera',
  'videography',
  'cinematography',
  'filmmaking',
  'image',
  'lens',
  'film',
  'photographing',
  'drone',
  'filmmaker',
  'aerial photography',
  'filming',
  'images',
  'image',
  'pic',
  'multi-media',
  'multimedia',
  'media',
  'picture',
  '4k camera',
  '4k',
];

export const graphics = [
  'graphics',
  'designer',
  'flyer',
  'flier',
  'poster',
  'church flier',
  'church flyer',
  'abstract',
  'abstract art',
  'photoshop',
  'adobe',
  'adobe photoshop',
  'adobe illustrator',
  'indesign',
  'adobe indesign',
  'vector art',
  'mockup design',
  'mockup',
];
